module.exports = {
  "prohibited": [
    "marcial1234", "cqgator", "nt92", "tkonda", "ajelacic16"
  ],
  "not_found": [
    "Carlos Fernandez",
    "Vivek Patel",
    "Nicole Smith",
    "Nicholas D'Agostino",
    "Xiao Wang",
    "Jessica Felde",
    "Ryan Bradley",
    "Sarah Long",
    "Derya Tansel",
    "Joshua Jones",
    "Robert Ryan",
    "Jeffrey Clark",
    "Zachery Cooper"
  ],
  "people": {
    "test": "Testing the UX",
    "dayron.acosta": "Dayron Acosta",
    "mlagono": "Manuel Lago",
    "d.orta.santana": "Dario Orta Santana",
    "mateo.pena": "Mateo Pena",
    "anuj.athavale": "Anuj Athavale",
    "smustafaj": "Syed-Mustafa Jamal",
    "singh2412": "Saurabh Singh",
    "barna03": "Nathan Barnavon",
    "bobelise": "Elana Bobelis",
    "nmarshall": "Nathan Marshall",
    "t.okwera": "Thomas Okwera",
    "nikescott": "Scott Thelemann",
    "leblanct": "Thomas Leblanc",
    "mmas93": "Michael Mas",
    "patelh1029": "Hari Patel",
    "mustafah": "Mustafa Hathiyari",
    "tianweihuang": "Tianwei Huang",
    "mohammadarezaei": "Mohammad Rezaei",
    "ky.shim": "Kyuyong Shim",
    "pedro.adorno1": "Pedro Adorno Maldonado",
    "bluel": "Logan Blue",
    "kkoepke": "Kristopher Koepke",
    "lfvargas14": "Luis Vargas",
    "vjadhav": "Vinay Jadhav",
    "zivr": "Case Winslow",
    "dcuppen": "Daan Cuppen",
    "vhagopian": "Victoria Hagopian",
    "skind": "Steffen Kind",
    "agarciaviciana": "Antonio Garcia Viciana",
    "ckeller": "Cara Keller",
    "jay.malaney": "Jay Malaney",
    "paulamelero": "Paula Melero",
    "frojo": "Francisco Rojo",
    "baigorria": "Lara Baigorria",
    "lindseynhaywood": "Lindsey Haywood",
    "shaanmjoshi": "Shaan Joshi",
    "seanzbarber": "Sean Barber",
    "argho33": "Arghya Das",
    "skhan94": "Sameer Khan",
    "j.lesagemoretti": "Jean Lesage Moretti",
    "mathew2109": "Mathew Martins",
    "basilnablus": "Basil Anabtawi",
    "zhossain": "Zabeer Hossain",
    "nelsonmaceda": "Nelson Maceda",
    "ttawfic": "Tiffany Tawfic",
    "macyweston": "Macy Weston",
    "jeromem": "Matthew Jerome",
    "umbranox": "Larry Lantz",
    "amessinger": "Alexander Messinger",
    "sebastian.rensch": "Sebastian Rensch",
    "fabb1237": "Fabio Biondolillo",
    "nduerr": "Nikolai Duerr",
    "fernandofranco": "Fernando Franco Crespo",
    "gabe.martins": "Gabriel Martins",
    "vishnu26": "Vishnu Sriram",
    "esander": "Prof. Erik Sander"
  }
}